### ISSUE TITLE
Browser error on upload: cannot authentificate over ajax calls

### ISSUE THREAD

**Issue by blessendor** [nicrame/Linux-Scripts#2]
Debian GNU/Linux 12
Nextcloud  'version' => '29.0.0.19',

There are a lot of errors on client side during bulk uploading.

Nextcloud installed with script
./nextcloud-ins.sh -lang=uk -mail=address -dm=FQDN -fdir=/opt/nextcloud-data

Help to debug the error.

There is no revers proxy used, all apache ports forwarded directly to the nextcloud (inside LXC).

**Comment by nicrame** [comment]
Nextcloud installer script is made for bare metal installs, and i believe it will not work correctly on any kind of containerization (lxc, docker or anything else). It was never testes to work on kind of them (since i even do not like them), and i even never used lxc at all. Also there is lack of logs from server (Apache logs, PHP logs, Nextcloud server logs).
What i would check if connections are made using https, and if such secure connection is established correctly. But i really have no idea how to debug things in lxc.

**Comment by blessendor** [comment]
LXC is almost bare metal, nothing special like it is with docker container. 
There are no errors in Apache logs.
Nextcloud windows client seems working well so far. There is only one user for only one bulk uploading task, so it could be some user's behaveur.

**Comment by nicrame** [comment]
As i checked, LXC uses own networking stack, that can be NAT-ed or bridged, so i would say that "almost" bare metal, is quiet a lot :) There are known problems with some Linux VM/Container configs and networking (with specific ethernet cards), so i was thinking that it may be this, but since it's AJAX problem, it may also mean some library problems on user installation. Nextcloud client app is not very good in my opinion. You may try Owncloud client (it is more or less compatible) and see, if it will work better. I've read many times that people use it with success when NC native client fails.
